// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4KSCMIShaMbToy7bTwm8Y-Us2A61KCuM',
    appId: '1:526485131653:web:298e7f4fa496006bc374ec',
    messagingSenderId: '526485131653',
    projectId: 'folha-de-ponto-58d17',
    authDomain: 'folha-de-ponto-58d17.firebaseapp.com',
    storageBucket: 'folha-de-ponto-58d17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLcGMYtQRZ8DbGIcbvqDj5iYRVyMk8vA',
    appId: '1:526485131653:android:ee11bdb17d07e84ec374ec',
    messagingSenderId: '526485131653',
    projectId: 'folha-de-ponto-58d17',
    storageBucket: 'folha-de-ponto-58d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGNZIW-zv5N5LcfL75BosZ4I3ptU1lUk',
    appId: '1:526485131653:ios:b606ef00dc884122c374ec',
    messagingSenderId: '526485131653',
    projectId: 'folha-de-ponto-58d17',
    storageBucket: 'folha-de-ponto-58d17.appspot.com',
    iosBundleId: 'com.example.fichaDePonto',
  );

}